version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
      - REACT_APP_API_URL=/api
    container_name: frontend_app
    ports:
      - "8081:80"
    volumes:
      - ./src:/app/src
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "8082:80"
    volumes:
      - ./dist:/usr/share/nginx/html 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
    - frontend
    networks:
    - frontend-network

networks:
  frontend-network:
    driver: bridge