

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=http://localhost:8080/api
    container_name: frontend_app
    networks:
      - frontend-network

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx-custom
      - ./dist:/app:ro
    depends_on:
      - frontend
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge